/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__grumpyai__0_0_1 = never;
export type PromptConfig__grumpyai__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__grumpyai__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__grumpyai__0_0_1;
  variables: PromptVariables__grumpyai__0_0_1;
  content: string;
};
export type Prompt__grumpyai = {
  name: 'Grumpy.ai';
  slug: 'grumpyai';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__grumpyai__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    grumpyai: Prompt__grumpyai;
  };
  globals: Globals;
};
